"""añadi columna

Revision ID: 5a2b2c174b95
Revises: d1067094652a
Create Date: 2022-11-25 12:02:29.594777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2b2c174b95'
down_revision = 'd1067094652a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_usuarios_phone'), 'usuarios', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_phone'), table_name='usuarios')
    op.drop_column('usuarios', 'phone')
    # ### end Alembic commands ###
